# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JackLeeProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.7.3'
pod 'SwiftyJSON'
pod 'SnapKit'
pod 'MJRefresh'
pod 'HandyJSON'
#banner滚动图片
#pod 'FSPagerView'
# 分页
pod 'DNSPageView', '~> 1.0.1'
#pod 'HandyJSON','~> 4.2.0-beta1'
# Pods for JackLeeProject

  target 'JackLeeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JackLeeProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
