# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JackLeeProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.7.3'
pod 'SwiftyJSON'
pod 'SnapKit'
# Pods for JackLeeProject

  target 'JackLeeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JackLeeProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
